"use client";
import {useMemo,useState} from "react";
const fields=[["guests", "מספר אורחים", "250", "אורחים"], ["plate", "מחיר מנה", "380", "₪"], ["photo", "צילום", "11000", "₪"], ["dj", "מוזיקה / DJ", "7000", "₪"], ["style", "לבוש ואיפור", "12000", "₪"], ["extra", "עיצוב ותוספות", "9000", "₪"]];
const initial=Object.fromEntries(fields.map(([key,,value])=>[key,Number(value)]));
const format=(n)=>new Intl.NumberFormat("he-IL",{maximumFractionDigits:0}).format(n);
export default function Home(){
 const [values,setValues]=useState(initial);
 const data=useMemo(()=>{ const food = values.guests * values.plate; const vendors=values.photo+values.dj+values.style+values.extra; const total=food+vendors; return { total, primary:'תקציב משוער', secondary:`₪${format(Math.round(total / Math.max(values.guests,1)))} לאורח`, rows:[['אולם ואוכל',food],['ספקים והפקה',vendors],['רשת ביטחון 10%',total*.1]] }; },[values]);
 return <main className="shell wedding"><nav className="nav"><div className="brand">חתונה בתכלס<span className="dot">.</span></div><a href="#calculator">למחשבון ↓</a></nav><section className="hero"><div><div className="eyebrow">WEDDING BUDGET · ישראל</div><h1>חתונה מדהימה.
תקציב שפוי.</h1><p className="lead">במקום לגלות את המספר רק אחרי שסוגרים ספקים — בונים רגע תמונה אמיתית של האירוע.</p></div><div className="heroArt" style={{'--hero':`url("https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1600&q=85")`}}><div className="floatTag"><span>תכנון חכם</span><b>מספרים שאפשר לסמוך עליהם</b></div></div></section><section id="calculator" className="calculator"><div className="panel"><h2>בואו נחשב</h2><p>שנו את המספרים — התוצאה מתעדכנת מיד.</p><div className="fields">{fields.map(([key,label,,unit])=><label key={key}>{label}<input aria-label={label} type="number" min="0" step="any" value={values[key]} onChange={e=>setValues(v=>({...v,[key]:Number(e.target.value)||0}))}/><small>{unit}</small></label>)}</div></div><aside className="result"><div><div className="resultLabel">{data.primary}</div><div className="total">₪{format(data.total)}</div><div className="secondary">{data.secondary}</div></div><div className="rows">{data.rows.map(([label,value])=><div className="row" key={label}><span>{label}</span><b>₪{format(value)}</b></div>)}</div></aside></section><section className="benefits"><div className="benefit"><i></i>רואים מחיר אמיתי לאורח</div><div className="benefit"><i></i>מתכננים רשת ביטחון</div><div className="benefit"><i></i>שולחים בקלות לשותף/ה</div></section><footer className="footer">חתונה בתכלס · תכנון פשוט. החלטות טובות יותר.</footer></main>}
